version: "3"
services:
  backend:
    build: ./backend
    ports:
      - 4001:4001
    environment:
      - NODE_ENV=production
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
